### ISSUE TITLE
[Question] Release questions and help offer

### ISSUE THREAD

**Issue by michaelwarren1106** [break-stuff/dia-date-picker#1]
Hey there!

Cory LaViska sent me here a while back because we've been looking for a good Lit date picker component for datepicker input components in our design systems. I see that you've been super active, and I'd love to help get this datepicker component to a good place for releasing on npm, even in an alpha state.

Do you have a checklist of items that are needed to be finished before publishing? If so, is there anything I can do to help? Could you publish your list and we can maybe work together to get toward a release?

Thanks in advance!

**Comment by break-stuff** [comment]
Thanks for reaching out! I think I was able to get the last big hurdle I was facing resolved (React wrappers). I will push forward and see if I can get the alp[ha out this weekend. I will also work on putting together a road map so people can start contributing if they would like. 

Are there any features in particular that you are looking for in a date picker? I'm always looking for ideas.

**Comment by break-stuff** [comment]
Here is a very rough draft of the docs, if you would like to take a look.

https://dia-date-picker.com/

**Comment by michaelwarren1106** [comment]
Thanks so much! The one feature I'd ask for at least a demo of, might be how this picker would be used to do a date range. If I had two of these pickers side by side and wanted to do a highlight of a range when the first date is in one picker and the second date is either in the same picker or the second one, how would this picker work with that?

Otherwise, if you publish a roadmap, I'd love to contribute!

**Comment by michaelwarren1106** [comment]
gonna close this issue and open others (and PRs if welcome) with suggestions
